class16-homework/homework1/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :hospitals do
    resources :patients do
      resources :medicines

      member do
        patch :waiting
        patch :doctor
        patch :xrays
        patch :surgery
        patch :paybill
        patch :leaving
        get :waiting
        get :doctor
        get :xrays
        get :surgery
        get :paybill
        get :leaving
      end
    end
  end

end

class16-homework/homework1/app/models/hospital.rb
class Hospital < ActiveRecord::Base
  has_many :patients
  has_many :medicines

  # @hospitals = Hospital.all
  accepts_nested_attributes_for :patients
end

class16-homework/homework1/app/models/patient.rb
class Patient < ActiveRecord::Base
  belongs_to :hospital
  has_many :medicines
  include Workflow
  workflow do 
    state :waiting do
      event :doctor, transitions_to: :doctor
      event :xray, transitions_to: :xray
      event :surgery, transitions_to: :surgery
      event :leaving, transitions_to: :leaving
    end

    state :doctor do
      event :doctor, transitions_to: :doctor
      event :xray, transitions_to: :xray
      event :surgery, transitions_to: :surgery
      event :paybill, transitions_to: :paybill
    end

    state :xray do
      event :surgery, transitions_to: :surgery
      event :doctor, transitions_to: :doctor
      event :paybill, transitions_to: :paybill
    end

    state :surgery do
      event :doctor, transitions_to: :doctor
      event :xray, transitions_to: :xray
      event :paybill, transitions_to: :paybill
    end

    state :paybill do
      event :leaving, transitions_to: :leaving
    end

    state :leaving 
  end

  WAITING = ["Send to Doctor", "Send to Xray", "Send to Surgery", "Leave"]
end

class16-homework/homework1/app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @hospital = Hospital.all
    @patient = Patient.where.not(workflow_state: "leaving")
    @patient_leaving = Patient.where(workflow_state: "leaving")
  end

end

class16-homework/homework1/app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  before_filter :find_hospital, only: [:show, :edit, :update, :destroy]
 
  def new
    @hospitals = Hospital.new
  end

  def create
    @hospitals = Hospital.create hospitals_params
    redirect_to root_path
  end

  def show
    @patients = @hospitals.patients
    @patients = @hospitals.patients.where.not(workflow_state: "leaving")
    @patient_leaving = @hospitals.patients.where(workflow_state: "leaving")
  end

  def edit
  end

  def update
  end

  def destroy
    @hospitals.delete
    redirect_to root_path
  end

  private
    def find_hospital
    @hospitals = Hospital.find params[:id]
  end

    def hospitals_params
    params.require(:hospital).permit(:name, :location, :description)
    end  
end

class16-homework/homework1/app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController
  before_filter :find_hospital
  before_filter :find_patient
  before_filter :find_medicine, only: [:show, :edit, :update, :destroy]
  def new
    @medicine = @patient.medicines.new
  end

  def create
    @medicine = @patient.medicines.create medicine_params
    redirect_to hospital_patient_path(@hospital, @patient)
  end

  def show
    @medicines = @patient.medicines
  end

  def edit
  end

  def update
    @medicine.update_attributes medicine_params
    redirect_to hospital_patient_path(@hospital, @patient)
  end 

  def destroy
    @medicine.delete
    redirect_to hospital_patient_path(@hospital, @patient)
  end


  private
    def medicine_params
    params.require(:medicine).permit(:name, :strength)
    end 

    def find_patient
      @patient = Patient.find params[:patient_id]
    end

    def find_medicine
      @medicine = Medicine.find params[:id]
    end 

     def find_hospital
      @hospital = Hospital.find params[:hospital_id]
    end
end

class16-homework/homework1/app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_filter :find_hospital
  before_filter :find_patient, only: [:show, :edit, :update, :destroy]
  def new
    @patient = @hospital.patients.new   
  end

  def create
    @patient = @hospital.patients.create patient_params
    redirect_to hospital_path(@hospital)
  end

  def edit
    @patient = Patient.find params[:id]
  end

  def update
    @patient = Patient.find params[:id]
    @patient.update_attributes patient_params
    redirect_to hospital_path(@hospital)
  end

  def show
    @patient = Patient.find params[:id]
    @medicine = Medicine.all
    @medicines = @patient.medicines
  end

  def destroy
    @patient = Patient.find params[:id]
    @patient.delete
    redirect_to hospital_path(hospital)
  end

  def doctor
    @patient = Patient.find params[:id]
    @patient.doctor!
    redirect_to hospital_path(@hospital)
  end

  def xrays
    @patient = Patient.find params[:id]
    @patient.xray!
    redirect_to hospital_path(@hospital)
  end

  def surgery
    @patient = Patient.find params[:id]
    @patient.surgery!
    redirect_to hospital_path(@hospital)
  end

  def paybill
    @patient = Patient.find params[:id]
    @patient.paybill!
    redirect_to hospital_path(@hospital)
  end

  def leaving
    @patient = Patient.find params[:id]
    @patient.leaving!
    redirect_to hospital_path(@hospital)
  end

  private
    def find_hospital
      @hospital = Hospital.find params[:hospital_id]
    end

    def find_patient
      @patient = @hospital.patients.find params[:id]
    end

    def patient_params
      params.require(:patient).permit(:name, :address, :phone_number, :hospital_id)
    end
end

class16-homework/homework1/app/views/hospitals/_form.html.haml
= form_for @hospitals do |f|
  =f.label :name
  =f.text_field :name
  =f.label :location
  =f.text_field :location
  =f.label :description
  =f.text_field :description

 


  %br
  =f.submit
%end
= link_to "Main Page", root_path

class16-homework/homework1/app/views/hospitals/edit.html.haml
%h1 Edit Hospitals
= render 'form'

class16-homework/homework1/app/views/hospitals/new.html.haml
%h1 hospitals
= render 'form'

class16-homework/homework1/app/views/hospitals/show.html.haml
= link_to "List of Hospitals", root_path
%br
= @hospitals.name
%br
= @hospitals.location
%br
= @hospitals.description
%br
%h1 Patients
%br
= link_to "New Patient", new_hospital_patient_path(@hospitals)
%br
  -@patients.each do |patient|
    %br
    = link_to patient.name, hospital_patient_path(@hospitals, patient)
    (#{patient.workflow_state})
    |
    = link_to "Edit Patient Info", edit_hospital_patient_path(@hospitals, patient)
    |
    = link_to "Delete", hospital_patient_path(@hospitals, patient), method: :delete
    |
    - if patient.workflow_state == 'waiting'
      =link_to "See Doctor", doctor_hospital_patient_path(@hospitals, patient), method: :patch
      |
      =link_to "Send to Xray", xrays_hospital_patient_path(@hospitals, patient), method: :patch
      |
      =link_to "Send to Surgery", surgery_hospital_patient_path(@hospitals, patient), method: :patch
    - elsif patient.workflow_state == "doctor"
      =link_to "Send to Xray", xrays_hospital_patient_path(@hospitals, patient), method: :patch
      |
      =link_to "Send to Surgery", surgery_hospital_patient_path(@hospitals, patient), method: :patch
      |
      =link_to "Send to Pay Bill", paybill_hospital_patient_path(@hospitals, patient), method: :patch
    - elsif patient.workflow_state == "xray"
      =link_to "Send to Surgery", surgery_hospital_patient_path(@hospitals, patient), method: :patch
      |
      =link_to "See Doctor", doctor_hospital_patient_path(@hospitals, patient), method: :patch
      |
      =link_to "Send to Pay Bill", paybill_hospital_patient_path(@hospitals, patient), method: :patch
    - elsif patient.workflow_state == "surgery"
      =link_to "Send to Xray", xrays_hospital_patient_path(@hospitals, patient), method: :patch
      |
      =link_to "See Doctor", doctor_hospital_patient_path(@hospitals, patient), method: :patch
      |
      =link_to "Send to Pay Bill", paybill_hospital_patient_path(@hospitals, patient), method: :patch
    - elsif patient.workflow_state == "paybill"
      =link_to "Leave Hospital", leaving_hospital_patient_path(@hospitals, patient), method: :patch 

%h2 Past Patients
-@patient_leaving.each do |patients|
  %br
  =patients.name