hw_project/homework1/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root'home#index'
  resources :locations do
    resources :courses do
      resources :assignments do
        member do
          get :new_comment
          post :add_comment
        end
        resources :submissions do
          member do
            get :new_comment
            post :add_comment
            patch :new
            patch :reviewing
            patch :complete
            patch :incomplete
          end
        end
      end
    end
  end

end

hw_project/homework1/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!
  before_filter :find_location
  before_filter :find_course, only: [:show, :update, :edit, :destroy]

  def new
    authorize! :create, Course
    @course = Course.new
  end

  def create
    authorize! :create, Course
    @course = @location.courses.create course_params
    success = @course.save
    if success == true
      flash[:notice] = "You entered an acceptable Course"
      redirect_to location_path(@location)
    else
      flash[:error] = "Not an acceptable Course"
      render :new
    end
  end

  def show
    authorize! :read, Assignment
    @assignment = @course.assignments
  end

  def edit
    authorize! :update, Course
  end

  def update
    authorize! :update, Course
    @course.update_attributes course_params
    redirect_to location_course_path(@location, @course)
  end

  def destroy
  end

  private
    def find_location
      @location = Location.find params[:location_id]
    end
    
    def find_course
      @course = Course.find params[:id]
    end

    def course_params
      params.require(:course).permit(:name, :location_id)
    end
end

hw_project/homework1/app/helpers/courses_helper.rb
module CoursesHelper
end

hw_project/homework1/app/views/courses/_form.html.haml
= simple_form_for [@location, @course] do |f|
  = f.input :name
  = f.button :submit

hw_project/homework1/app/views/courses/edit.html.haml
%h1 Edit Course
= render 'form'
= link_to "Cancel", location_course_path(@location, @course)

hw_project/homework1/app/views/courses/new.html.haml
%h1 Add New Course
= render 'form'
=link_to "Cancel", locations_path

hw_project/homework1/app/views/courses/show.html.haml
%link{:href => "//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css", :rel => "stylesheet"}/

.page-container
  / top navbar
  .navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
    .container
      .navbar-header
        %button.navbar-toggle{"data-target" => ".sidebar-nav", "data-toggle" => "offcanvas", :type => "button"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => "/"} Student Homework Tracker
        .headerrightcontainer
          .navbar-brand
            - if user_signed_in? 
              = link_to('Logout', destroy_user_session_path, :method => :delete)
            - else
              = link_to('Login', new_user_session_path)
  .container
    .row.row-offcanvas.row-offcanvas-left
      / sidebar
      #sidebar.col-xs-6.col-sm-3.sidebar-offcanvas{:role => "navigation"}
        %div{"data-offset-bottom" => "90", "data-offset-top" => "45", "data-spy" => "affix"}
          %ul#sidebar-nav.nav
            
            %li
              %a{:href => "/"} Home
            %li
              %a{:href => "/locations"} Back To Locations
            %li
              =link_to "Back To Courses", location_path(@location)
            -if current_user.admin?
              %li
                =link_to "Add Assignment", new_location_course_assignment_path(@location, @course)
              %li
                =link_to "Edit Course", edit_location_course_path(@location, @course) 
      / main area
      .col-xs-12.col-sm-9{"data-spy" => "scroll", "data-target" => "#sidebar-nav"}
        %h1 #{@location.name} #{@course.name} Assignments
        -@assignment.each do |assignment|
          %br
          =link_to "#{assignment.name}", location_course_assignment_path(@location, @course, assignment)

        %h1 Students in #{@location.name} #{@course.name}

        -@course.users.each do |user|
          %br
          = user.name
      / /.col-xs-12 main
    / /.row
  / /.container
/ /.page-container
#footer
  / footer
  .container
    .row
      %ul.list-unstyled