class14-homework/homework1/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :patients do

    member do
      patch :waiting
      patch :doctor
      patch :xrays
      patch :surgery
      patch :paybill
      patch :leaving
      get :ad_info
    end
  end

end

class14-homework/homework1/app/models/patient.rb
class Patient < ActiveRecord::Base

  include Workflow 
  workflow do 
    state :waiting do
      event :doctor, transitions_to: :doctor
      event :xray, transitions_to: :xray
      event :surgery, transitions_to: :surgery
      event :leaving, transitions_to: :leaving
    end

    state :doctor do
      event :xray, transitions_to: :xray
      event :surgery, transitions_to: :surgery
      event :paybill, transitions_to: :paybill
    end

    state :xray do
      event :surgery, transitions_to: :surgery
      event :doctor, transitions_to: :doctor
      event :paybill, transitions_to: :paybill
    end

    state :surgery do
      event :doctor, transitions_to: :doctor
      event :xray, transitions_to: :xray
      event :paybill, transitions_to: :paybill
    end

    state :paybill do
      event :leaving, transitions_to: :leaving
    end

    state :leaving 
      event :leaving, transitions_to: :leaving
  end

  WAITING = ["Send to Doctor", "Send to Xray", "Send to Surgery", "Leave"]
  DOCTOR = ["Send to Xray", "Send to Surgery", "Paybill"]
  XRAY = ["Send to Surgery", "Send to Doctor", "Paybill"]
  SURGERY = ["Send to Doctor", "Send to Xray", "Paybill"]
  PAYBILL = ["Leave"]
end

class14-homework/homework1/app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @patient = Patient.where.not(workflow_state: "leaving")
    @patient_leaving = Patient.where(workflow_state: "leaving")
  end

end

class14-homework/homework1/app/controllers/patients_controller.rb
class PatientsController < ApplicationController

before_filter :find_patient, only: [:edit, :update, :show, :destroy, :doctor, :xrays, :surgery, :paybill, :leaving, :ad_info]

  def new
    @patient = Patient.new   
  end 

  def create
    @patient = Patient.create patient_params
    redirect_to root_path
  end

  def edit
  end

  def update
    @patient.update_attributes patient_params
    redirect_to root_path
  end

  def show
  end

  def destroy
    @patient.delete
    redirect_to root_path
  end

  def doctor
    @patient.doctor!
    redirect_to root_path
  end

  def xrays
    @patient.xray!
    redirect_to root_path
  end

  def surgery
    @patient.surgery!
    redirect_to root_path
  end

  def paybill
    @patient.paybill!
    redirect_to root_path
  end

  def leaving
    @patient.leaving!
    redirect_to ad_info_patient_path
  end

  def ad_info
  end

  private
    def patient_params
      params.require(:patient).permit(:name, :address, :phone_number, :ad_info)
    end

    def find_patient
      @patient = Patient.find params[:id]
    end

end

class14-homework/homework1/app/views/home/index.html.haml
%h1 Hospital

= link_to 'New Patients', new_patient_path

%br
%br
%ul
-@patient.each do |patient|
  %li
  =patient.name
  (#{patient.workflow_state})
  =link_to "Edit", edit_patient_path(patient)
  |
  =link_to "Show Patient Info", patient_path(patient)
  |
  =link_to "Remove Patient", patient_path(patient), method: :delete
  %br
  =form_for patient do |f| 
    - if patient.workflow_state == 'waiting'
      = f.label :workflow_state
      = f.select :workflow_state, options_for_select(Patient::WAITING), include_blank: '--- Select ---'

    - elsif patient.workflow_state == "doctor"
      = f.label :workflow_state
      = f.select :workflow_state, options_for_select(Patient::DOCTOR), include_blank: '--- Select ---'

    - elsif patient.workflow_state == "xray"
      = f.label :workflow_state
      = f.select :workflow_state, options_for_select(Patient::XRAY), include_blank: '--- Select ---'

    - elsif patient.workflow_state == "surgery"
      = f.label :workflow_state
      = f.select :workflow_state, options_for_select(Patient::SURGERY), include_blank: '--- Select ---'
 
    - elsif patient.workflow_state == "paybill"
      = f.label :workflow_state
      = f.select :workflow_state, options_for_select(Patient::PAYBILL), include_blank: '--- Select ---'
   
    - elsif patient.workflow_state == "leaving"
    = f.submit

%h2 Past Patients
-@patient_leaving.each do |patients|
  %hr
  =patients.name
  |
  =link_to "Show Patient Info", patient_path(patients)